/* Generated by tools/esp-idf-contracts.ts from contracts/spec/idf-native.ts. Do not edit. */
#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
#define PJS_ABI_ASSERT static_assert
#define PJS_ABI_ALIGNOF alignof
#else
#define PJS_ABI_ASSERT _Static_assert
#define PJS_ABI_ALIGNOF _Alignof
#endif

typedef struct {
  size_t struct_size;
  uint32_t logical_width;
  uint32_t logical_height;
  uint32_t raster_density;
  uint32_t tick_hz;
} pocketjs_ui_core_config_t;
PJS_ABI_ASSERT(sizeof(pocketjs_ui_core_config_t) == (sizeof(void *) == 4 ? 20 : 24), "pocketjs_ui_core_config_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_ui_core_config_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_core_config_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_core_config_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_ui_core_config_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_core_config_t, logical_width) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_core_config_t.logical_width");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_core_config_t, logical_height) == (sizeof(void *) == 4 ? 8 : 12), "pocketjs_ui_core_config_t.logical_height");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_core_config_t, raster_density) == (sizeof(void *) == 4 ? 12 : 16), "pocketjs_ui_core_config_t.raster_density");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_core_config_t, tick_hz) == (sizeof(void *) == 4 ? 16 : 20), "pocketjs_ui_core_config_t.tick_hz");

typedef struct {
  size_t struct_size;
  uint32_t kind;
  const uint8_t * data;
  size_t size;
} pocketjs_ui_asset_t;
PJS_ABI_ASSERT(sizeof(pocketjs_ui_asset_t) == (sizeof(void *) == 4 ? 16 : 32), "pocketjs_ui_asset_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_ui_asset_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_asset_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_asset_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_ui_asset_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_asset_t, kind) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_asset_t.kind");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_asset_t, data) == (sizeof(void *) == 4 ? 8 : 16), "pocketjs_ui_asset_t.data");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_asset_t, size) == (sizeof(void *) == 4 ? 12 : 24), "pocketjs_ui_asset_t.size");

typedef struct {
  size_t struct_size;
  /* Borrow generation changes on every draw, mutation, and tick. */
  uint64_t epoch;
  uint64_t raster_revision;
  uint32_t logical_width;
  uint32_t logical_height;
  uint32_t raster_density;
  const uint32_t * draw_words;
  size_t draw_word_count;
  /* Opaque C bridge; callers must not inspect or dereference. */
  void * _private_core;
} pocketjs_ui_frame_view_t;
PJS_ABI_ASSERT(sizeof(pocketjs_ui_frame_view_t) == (sizeof(void *) == 4 ? 48 : 64), "pocketjs_ui_frame_view_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_ui_frame_view_t) == (sizeof(void *) == 4 ? 8 : 8), "pocketjs_ui_frame_view_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_ui_frame_view_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, epoch) == (sizeof(void *) == 4 ? 8 : 8), "pocketjs_ui_frame_view_t.epoch");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, raster_revision) == (sizeof(void *) == 4 ? 16 : 16), "pocketjs_ui_frame_view_t.raster_revision");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, logical_width) == (sizeof(void *) == 4 ? 24 : 24), "pocketjs_ui_frame_view_t.logical_width");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, logical_height) == (sizeof(void *) == 4 ? 28 : 28), "pocketjs_ui_frame_view_t.logical_height");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, raster_density) == (sizeof(void *) == 4 ? 32 : 32), "pocketjs_ui_frame_view_t.raster_density");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, draw_words) == (sizeof(void *) == 4 ? 36 : 40), "pocketjs_ui_frame_view_t.draw_words");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, draw_word_count) == (sizeof(void *) == 4 ? 40 : 48), "pocketjs_ui_frame_view_t.draw_word_count");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_frame_view_t, _private_core) == (sizeof(void *) == 4 ? 44 : 56), "pocketjs_ui_frame_view_t._private_core");

typedef struct {
  size_t struct_size;
  const uint8_t * pixels;
  size_t pixel_bytes;
  uint32_t width;
  uint32_t height;
  uint32_t psm;
  const uint8_t * palette;
  size_t palette_bytes;
  uint64_t revision;
  bool linear;
} pocketjs_ui_texture_view_t;
PJS_ABI_ASSERT(sizeof(pocketjs_ui_texture_view_t) == (sizeof(void *) == 4 ? 48 : 72), "pocketjs_ui_texture_view_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_ui_texture_view_t) == (sizeof(void *) == 4 ? 8 : 8), "pocketjs_ui_texture_view_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_ui_texture_view_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, pixels) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_texture_view_t.pixels");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, pixel_bytes) == (sizeof(void *) == 4 ? 8 : 16), "pocketjs_ui_texture_view_t.pixel_bytes");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, width) == (sizeof(void *) == 4 ? 12 : 24), "pocketjs_ui_texture_view_t.width");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, height) == (sizeof(void *) == 4 ? 16 : 28), "pocketjs_ui_texture_view_t.height");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, psm) == (sizeof(void *) == 4 ? 20 : 32), "pocketjs_ui_texture_view_t.psm");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, palette) == (sizeof(void *) == 4 ? 24 : 40), "pocketjs_ui_texture_view_t.palette");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, palette_bytes) == (sizeof(void *) == 4 ? 28 : 48), "pocketjs_ui_texture_view_t.palette_bytes");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, revision) == (sizeof(void *) == 4 ? 32 : 56), "pocketjs_ui_texture_view_t.revision");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_texture_view_t, linear) == (sizeof(void *) == 4 ? 40 : 64), "pocketjs_ui_texture_view_t.linear");

typedef struct {
  size_t struct_size;
  const uint8_t * bitmap;
  size_t bitmap_bytes;
  uint32_t cell_width;
  uint32_t cell_height;
  uint32_t raster_density;
  uint32_t glyph_count;
} pocketjs_ui_font_view_t;
PJS_ABI_ASSERT(sizeof(pocketjs_ui_font_view_t) == (sizeof(void *) == 4 ? 28 : 40), "pocketjs_ui_font_view_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_ui_font_view_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_font_view_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_ui_font_view_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, bitmap) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_ui_font_view_t.bitmap");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, bitmap_bytes) == (sizeof(void *) == 4 ? 8 : 16), "pocketjs_ui_font_view_t.bitmap_bytes");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, cell_width) == (sizeof(void *) == 4 ? 12 : 24), "pocketjs_ui_font_view_t.cell_width");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, cell_height) == (sizeof(void *) == 4 ? 16 : 28), "pocketjs_ui_font_view_t.cell_height");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, raster_density) == (sizeof(void *) == 4 ? 20 : 32), "pocketjs_ui_font_view_t.raster_density");
PJS_ABI_ASSERT(offsetof(pocketjs_ui_font_view_t, glyph_count) == (sizeof(void *) == 4 ? 24 : 36), "pocketjs_ui_font_view_t.glyph_count");

#undef PJS_ABI_ASSERT
#undef PJS_ABI_ALIGNOF
