/* Generated by tools/esp-idf-contracts.ts from contracts/spec/idf-native.ts. Do not edit. */
#pragma once
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
#define PJS_ABI_ASSERT static_assert
#define PJS_ABI_ALIGNOF alignof
#else
#define PJS_ABI_ASSERT _Static_assert
#define PJS_ABI_ALIGNOF _Alignof
#endif
#define POCKETJS_RGB565_MAX_DAMAGE_REGIONS 8U

typedef struct {
  size_t struct_size;
  uint32_t scale;
  uint32_t min_fill_pixels;
  uint32_t min_blend_pixels;
  uint32_t min_srm_pixels;
} pocketjs_rgb565_renderer_config_t;
PJS_ABI_ASSERT(sizeof(pocketjs_rgb565_renderer_config_t) == (sizeof(void *) == 4 ? 20 : 24), "pocketjs_rgb565_renderer_config_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_rgb565_renderer_config_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_renderer_config_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_renderer_config_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_rgb565_renderer_config_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_renderer_config_t, scale) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_renderer_config_t.scale");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_renderer_config_t, min_fill_pixels) == (sizeof(void *) == 4 ? 8 : 12), "pocketjs_rgb565_renderer_config_t.min_fill_pixels");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_renderer_config_t, min_blend_pixels) == (sizeof(void *) == 4 ? 12 : 16), "pocketjs_rgb565_renderer_config_t.min_blend_pixels");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_renderer_config_t, min_srm_pixels) == (sizeof(void *) == 4 ? 16 : 20), "pocketjs_rgb565_renderer_config_t.min_srm_pixels");

typedef struct {
  uint32_t x;
  uint32_t y;
  uint32_t width;
  uint32_t height;
} pocketjs_rgb565_rect_t;
PJS_ABI_ASSERT(sizeof(pocketjs_rgb565_rect_t) == (sizeof(void *) == 4 ? 16 : 16), "pocketjs_rgb565_rect_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_rgb565_rect_t) == (sizeof(void *) == 4 ? 4 : 4), "pocketjs_rgb565_rect_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_rect_t, x) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_rgb565_rect_t.x");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_rect_t, y) == (sizeof(void *) == 4 ? 4 : 4), "pocketjs_rgb565_rect_t.y");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_rect_t, width) == (sizeof(void *) == 4 ? 8 : 8), "pocketjs_rgb565_rect_t.width");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_rect_t, height) == (sizeof(void *) == 4 ? 12 : 12), "pocketjs_rgb565_rect_t.height");

typedef struct {
  size_t struct_size;
  uint32_t region_count;
  bool full_redraw;
  pocketjs_rgb565_rect_t regions[8];
} pocketjs_rgb565_damage_plan_t;
PJS_ABI_ASSERT(sizeof(pocketjs_rgb565_damage_plan_t) == (sizeof(void *) == 4 ? 140 : 144), "pocketjs_rgb565_damage_plan_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_rgb565_damage_plan_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_damage_plan_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_damage_plan_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_rgb565_damage_plan_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_damage_plan_t, region_count) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_damage_plan_t.region_count");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_damage_plan_t, full_redraw) == (sizeof(void *) == 4 ? 8 : 12), "pocketjs_rgb565_damage_plan_t.full_redraw");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_damage_plan_t, regions) == (sizeof(void *) == 4 ? 12 : 16), "pocketjs_rgb565_damage_plan_t.regions");

typedef struct {
  size_t struct_size;
  uint32_t ppa_fills;
  uint32_t ppa_blends;
  uint32_t ppa_srm;
  uint32_t software_ops;
  uint32_t software_words;
  uint32_t damage_regions;
  uint32_t damage_pixels;
  pocketjs_rgb565_rect_t damage_bounds;
  bool full_redraw;
} pocketjs_rgb565_render_stats_t;
PJS_ABI_ASSERT(sizeof(pocketjs_rgb565_render_stats_t) == (sizeof(void *) == 4 ? 52 : 56), "pocketjs_rgb565_render_stats_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_rgb565_render_stats_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_render_stats_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_rgb565_render_stats_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, ppa_fills) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_render_stats_t.ppa_fills");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, ppa_blends) == (sizeof(void *) == 4 ? 8 : 12), "pocketjs_rgb565_render_stats_t.ppa_blends");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, ppa_srm) == (sizeof(void *) == 4 ? 12 : 16), "pocketjs_rgb565_render_stats_t.ppa_srm");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, software_ops) == (sizeof(void *) == 4 ? 16 : 20), "pocketjs_rgb565_render_stats_t.software_ops");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, software_words) == (sizeof(void *) == 4 ? 20 : 24), "pocketjs_rgb565_render_stats_t.software_words");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, damage_regions) == (sizeof(void *) == 4 ? 24 : 28), "pocketjs_rgb565_render_stats_t.damage_regions");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, damage_pixels) == (sizeof(void *) == 4 ? 28 : 32), "pocketjs_rgb565_render_stats_t.damage_pixels");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, damage_bounds) == (sizeof(void *) == 4 ? 32 : 36), "pocketjs_rgb565_render_stats_t.damage_bounds");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_render_stats_t, full_redraw) == (sizeof(void *) == 4 ? 48 : 52), "pocketjs_rgb565_render_stats_t.full_redraw");

typedef bool (*pocketjs_rgb565_fill_fn)(void *, uint16_t *, size_t, uint32_t, uint32_t, pocketjs_rgb565_rect_t, uint16_t);

typedef bool (*pocketjs_rgb565_blend_fn)(void *, uint16_t *, size_t, uint32_t, uint32_t, const uint8_t *, size_t, pocketjs_rgb565_rect_t, uint8_t, uint8_t, uint8_t, uint8_t);

typedef bool (*pocketjs_rgb565_srm_fn)(void *, uint16_t *, size_t, uint32_t, uint32_t, const uint8_t *, size_t, uint32_t, uint32_t, pocketjs_rgb565_rect_t, pocketjs_rgb565_rect_t, uint32_t, bool, bool);

typedef struct {
  size_t struct_size;
  void * user_data;
  pocketjs_rgb565_fill_fn fill_rgb565;
  pocketjs_rgb565_blend_fn blend_a8_rgb565;
  pocketjs_rgb565_srm_fn srm_psm5650_rgb565;
} pocketjs_rgb565_accelerator_t;
PJS_ABI_ASSERT(sizeof(pocketjs_rgb565_accelerator_t) == (sizeof(void *) == 4 ? 20 : 40), "pocketjs_rgb565_accelerator_t size");
PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(pocketjs_rgb565_accelerator_t) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_accelerator_t alignment");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_accelerator_t, struct_size) == (sizeof(void *) == 4 ? 0 : 0), "pocketjs_rgb565_accelerator_t.struct_size");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_accelerator_t, user_data) == (sizeof(void *) == 4 ? 4 : 8), "pocketjs_rgb565_accelerator_t.user_data");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_accelerator_t, fill_rgb565) == (sizeof(void *) == 4 ? 8 : 16), "pocketjs_rgb565_accelerator_t.fill_rgb565");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_accelerator_t, blend_a8_rgb565) == (sizeof(void *) == 4 ? 12 : 24), "pocketjs_rgb565_accelerator_t.blend_a8_rgb565");
PJS_ABI_ASSERT(offsetof(pocketjs_rgb565_accelerator_t, srm_psm5650_rgb565) == (sizeof(void *) == 4 ? 16 : 32), "pocketjs_rgb565_accelerator_t.srm_psm5650_rgb565");

#undef PJS_ABI_ASSERT
#undef PJS_ABI_ALIGNOF
